
# This file was *autogenerated* from the file keyGeneration.sage
from sage.all_cmdline import *   # import sage library

# Generates an answer key file. Takes in the Module number and Version (A, B, or C).
def createAnswerKeyFile(moduleNumber, version):
    keyFile = open('../Keys/key' + str(moduleNumber) + str(version) + '.tex', 'w')
    keyFile.write("\\documentclass{article}[12pt] \n")
    keyFile.write("\\usepackage{multicol, enumerate, enumitem, hyperref, color, soul, setspace, parskip, fancyhdr, amssymb, amsthm, amsmath, bbm, latexsym, units, mathtools} \n")
    keyFile.write("\\everymath{\\displaystyle} \n")
    keyFile.write("\\usepackage[headsep=0.5cm,headheight=0cm, left=1 in,right= 1 in,top= 1 in,bottom= 1 in]{geometry} \n")
    keyFile.write("\\begin{document} \n\n")
    keyFile.write("This is the Answer Key for Module " + str(moduleNumber) + " Version " + str(version) + "\n\n")
    keyFile.write("----------------------------------------------- \n \n")
    keyFile.close()

def writeQuestionToFile(moduleNumber, version, problemNumber, stem, problem):
    keyFile = open('../Keys/key' + str(moduleNumber) + str(version) + '.tex', 'a')
    keyFile.write("%d. %s\n" % (problemNumber, stem))
    keyFile.write("$$ %s $$ \n" % problem)
    keyFile.close()

def writePictureQuestionToFile(moduleNumber, version, problemNumber, stem, problem):
    keyFile = open('../Keys/key' + str(moduleNumber) + str(version) + '.tex', 'a')
    keyFile.write("%d. %s\n" % (problemNumber, stem))
    keyFile.write("%s \n" % problem)
    keyFile.close()

def writeSolutionAndOptionsToFile(moduleNumber, version, solution, items, itemComments):
    keyFile = open('../Keys/key' + str(moduleNumber) + str(version) + '.tex', 'a')
    keyFile.write("The solution is $ %s $ \n\n" %solution)
    keyFile.write("\\begin{enumerate}[label=\\Alph*.] \n")
    for i in xrange(len(items)):
        keyFile.write("\\item $ %s $ \n\n" %items[i])
        keyFile.write(" %s \n" %itemComments[i])
    keyFile.write("\\end{enumerate} \n \n")
    keyFile.close()

def writePictureSolutionAndPictureOptionsToFile(moduleNumber, version, solutionName, figureNames, itemComments):
    keyFile = open('../Keys/key' + str(moduleNumber) + str(version) + '.tex', 'a')
    keyFile.write("The solution is  \n")
    keyFile.write("\\begin{center}")
    keyFile.write("\\includegraphics[scale=0.5]{../Figures/question%s%s.png}" %(solutionName, version))
    keyFile.write("\\end{center}")
    keyFile.write("\\begin{enumerate}[label=\\Alph*.] \n")
    for i in xrange(len(figureNames)):
        keyFile.write("\\item %s \n" %itemComments[i])
        keyFile.write("\\begin{center}")
        keyFile.write("\\includegraphics[scale=0.5]{../Figures/question%s%s.png}" %(figureNames[i], version))
        keyFile.write("\\end{center} \n \n")
    keyFile.write("\\end{enumerate} \n \n")
    keyFile.close()

def writeCommentsToFile(moduleNumber, version, comment):
    keyFile = open('../Keys/key' + str(moduleNumber) + str(version) + '.tex', 'a')
    keyFile.write("%s\n\n" %comment)
    keyFile.write("-----------------------------------------------\n\n")
    keyFile.close()

def completeKey(moduleNumber, version):
    keyFile = open('../Keys/key' + str(moduleNumber) + str(version) + '.tex', 'a')
    keyFile.write("\\end{document}")
    keyFile.close()

def includePictureInKey(moduleNumber, figureName, version):
    keyFile = open('../Keys/key' + str(moduleNumber) + str(version) + '.tex', 'a')
    keyFile.write("\\begin{center}")
    keyFile.write("\\includegraphics[scale=0.5]{../Figures/question%s%s.png}" %(figureName, version))
    keyFile.write("\\end{center}")
    keyFile.close()

