## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file /media/archdoc/7636-BC29/improvedExamGeneration/M03Inequality/Module3B.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_28 = Integer(28); _sage_const_29 = Integer(29); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_25 = Integer(25); _sage_const_42 = Integer(42); _sage_const_65 = Integer(65); _sage_const_62 = Integer(62); _sage_const_47 = Integer(47); _sage_const_85 = Integer(85); _sage_const_80 = Integer(80); _sage_const_82 = Integer(82); _sage_const_33 = Integer(33); _sage_const_35 = Integer(35); _sage_const_119 = Integer(119); _sage_const_32 = Integer(32); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_59 = Integer(59); _sage_const_14 = Integer(14); _sage_const_31 = Integer(31); _sage_const_30 = Integer(30); _sage_const_19 = Integer(19); _sage_const_18 = Integer(18); _sage_const_15 = Integer(15); _sage_const_34 = Integer(34); _sage_const_37 = Integer(37); _sage_const_36 = Integer(36); _sage_const_122 = Integer(122); _sage_const_99 = Integer(99); _sage_const_125 = Integer(125); _sage_const_38 = Integer(38); _sage_const_104 = Integer(104); _sage_const_107 = Integer(107); _sage_const_137 = Integer(137)## This file (Module3B.sagetex.sage) was *autogenerated* from Module3B.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('Module3B', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_34 
_st_.blockbegin()
try:
 load("../Code/generalPurposeMethods.sage")
 load("../Code/keyGeneration.sage")
except:
 _st_.goboom(_sage_const_37 )
_st_.blockend()
_st_.current_tex_line = _sage_const_42 
_st_.blockbegin()
try:
 moduleNumber = _sage_const_3 
 version = "B"
 problemNumber = _sage_const_11 
 load("../Code/inequality/describeSet.sage")
except:
 _st_.goboom(_sage_const_47 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_0 , latex(displayStem))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_1 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_2 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_3 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_4 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_5 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_59 )
_st_.current_tex_line = _sage_const_62 
_st_.blockbegin()
try:
 problemNumber = _sage_const_12 
 load("../Code/inequality/solveIntegerInequality.sage")
except:
 _st_.goboom(_sage_const_65 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_6 , latex(displayStem))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_7 , latex(displayLeftFactor))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_8 , latex(displayRightFactor))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_9 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_10 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_11 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_12 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_13 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_80 )
_st_.current_tex_line = _sage_const_82 
_st_.blockbegin()
try:
 problemNumber = _sage_const_13 
 load("../Code/inequality/solveRationalInequality.sage")
except:
 _st_.goboom(_sage_const_85 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_14 , latex(displayStem))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_15 , latex(displayLeftFactor))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_16 , latex(displayRightFactor))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_17 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_18 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_19 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_20 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_21 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_99 )
_st_.current_tex_line = _sage_const_104 
_st_.blockbegin()
try:
 problemNumber = _sage_const_14 
 load("../Code/inequality/solveCompoundOR.sage")
except:
 _st_.goboom(_sage_const_107 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_119 
 _st_.inline(_sage_const_22 , latex(displayStem))
except:
 _st_.goboom(_sage_const_119 )
try:
 _st_.current_tex_line = _sage_const_119 
 _st_.inline(_sage_const_23 , latex(displayLeftFactor))
except:
 _st_.goboom(_sage_const_119 )
try:
 _st_.current_tex_line = _sage_const_119 
 _st_.inline(_sage_const_24 , latex(displayRightFactor))
except:
 _st_.goboom(_sage_const_119 )
try:
 _st_.current_tex_line = _sage_const_119 
 _st_.inline(_sage_const_25 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_119 )
try:
 _st_.current_tex_line = _sage_const_119 
 _st_.inline(_sage_const_26 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_119 )
try:
 _st_.current_tex_line = _sage_const_119 
 _st_.inline(_sage_const_27 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_119 )
try:
 _st_.current_tex_line = _sage_const_119 
 _st_.inline(_sage_const_28 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_119 )
try:
 _st_.current_tex_line = _sage_const_119 
 _st_.inline(_sage_const_29 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_119 )
_st_.current_tex_line = _sage_const_122 
_st_.blockbegin()
try:
 problemNumber = _sage_const_15 
 load("../Code/inequality/solveCompoundAND.sage")
except:
 _st_.goboom(_sage_const_125 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_137 
 _st_.inline(_sage_const_30 , latex(displayStem))
except:
 _st_.goboom(_sage_const_137 )
try:
 _st_.current_tex_line = _sage_const_137 
 _st_.inline(_sage_const_31 , latex(AndInequalityLeft))
except:
 _st_.goboom(_sage_const_137 )
try:
 _st_.current_tex_line = _sage_const_137 
 _st_.inline(_sage_const_32 , latex(AndInequalityMiddle))
except:
 _st_.goboom(_sage_const_137 )
try:
 _st_.current_tex_line = _sage_const_137 
 _st_.inline(_sage_const_33 , latex(AndInequalityRight))
except:
 _st_.goboom(_sage_const_137 )
try:
 _st_.current_tex_line = _sage_const_137 
 _st_.inline(_sage_const_34 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_137 )
try:
 _st_.current_tex_line = _sage_const_137 
 _st_.inline(_sage_const_35 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_137 )
try:
 _st_.current_tex_line = _sage_const_137 
 _st_.inline(_sage_const_36 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_137 )
try:
 _st_.current_tex_line = _sage_const_137 
 _st_.inline(_sage_const_37 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_137 )
try:
 _st_.current_tex_line = _sage_const_137 
 _st_.inline(_sage_const_38 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_137 )
_st_.endofdoc()

