## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file /media/archdoc/7636-BC29/improvedExamGeneration/M02Linear/Module2B.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_38 = Integer(38); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_28 = Integer(28); _sage_const_29 = Integer(29); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_19 = Integer(19); _sage_const_24 = Integer(24); _sage_const_25 = Integer(25); _sage_const_66 = Integer(66); _sage_const_41 = Integer(41); _sage_const_42 = Integer(42); _sage_const_32 = Integer(32); _sage_const_88 = Integer(88); _sage_const_63 = Integer(63); _sage_const_47 = Integer(47); _sage_const_85 = Integer(85); _sage_const_111 = Integer(111); _sage_const_81 = Integer(81); _sage_const_27 = Integer(27); _sage_const_40 = Integer(40); _sage_const_45 = Integer(45); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_31 = Integer(31); _sage_const_30 = Integer(30); _sage_const_33 = Integer(33); _sage_const_18 = Integer(18); _sage_const_35 = Integer(35); _sage_const_34 = Integer(34); _sage_const_37 = Integer(37); _sage_const_36 = Integer(36); _sage_const_108 = Integer(108); _sage_const_39 = Integer(39); _sage_const_126 = Integer(126); _sage_const_43 = Integer(43); _sage_const_129 = Integer(129); _sage_const_61 = Integer(61); _sage_const_105 = Integer(105); _sage_const_44 = Integer(44); _sage_const_148 = Integer(148); _sage_const_132 = Integer(132)## This file (Module2B.sagetex.sage) was *autogenerated* from Module2B.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('Module2B', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_33 
_st_.blockbegin()
try:
 load("../Code/generalPurposeMethods.sage")
 load("../Code/keyGeneration.sage")
except:
 _st_.goboom(_sage_const_36 )
_st_.blockend()
_st_.current_tex_line = _sage_const_42 
_st_.blockbegin()
try:
 moduleNumber = _sage_const_2 
 version = "B"
 problemNumber = _sage_const_6 
 load("../Code/linear/linearTwoPoints.sage")
except:
 _st_.goboom(_sage_const_47 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_61 
 _st_.inline(_sage_const_0 , latex(displayStem))
except:
 _st_.goboom(_sage_const_61 )
try:
 _st_.current_tex_line = _sage_const_61 
 _st_.inline(_sage_const_1 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_61 )
try:
 _st_.current_tex_line = _sage_const_61 
 _st_.inline(_sage_const_2 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_61 )
try:
 _st_.current_tex_line = _sage_const_61 
 _st_.inline(_sage_const_3 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_61 )
try:
 _st_.current_tex_line = _sage_const_61 
 _st_.inline(_sage_const_4 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_61 )
try:
 _st_.current_tex_line = _sage_const_61 
 _st_.inline(_sage_const_5 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_61 )
try:
 _st_.current_tex_line = _sage_const_61 
 _st_.inline(_sage_const_6 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_61 )
_st_.current_tex_line = _sage_const_63 
_st_.blockbegin()
try:
 problemNumber = _sage_const_7 
 load("../Code/linear/linearGraphToStandard.sage")
except:
 _st_.goboom(_sage_const_66 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_7 , latex(displayStem))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_8 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_9 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_10 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_11 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_12 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_81 )
_st_.current_tex_line = _sage_const_85 
_st_.blockbegin()
try:
 problemNumber = _sage_const_8 
 load("../Code/linear/linearParOrPer.sage")
except:
 _st_.goboom(_sage_const_88 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_13 , latex(displayStem))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_14 , latex(lineType))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_15 , latex(standardFormParOrPer))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_16 , latex(cCoeffInt))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_17 , latex(point[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_18 , latex(point[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_19 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_20 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_21 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_22 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_23 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_105 )
_st_.current_tex_line = _sage_const_108 
_st_.blockbegin()
try:
 problemNumber = _sage_const_9 
 load("../Code/linear/solveIntegerLinear.sage")
except:
 _st_.goboom(_sage_const_111 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_24 , latex(displayStem))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_25 , latex(blocks[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_26 , latex(blocks[_sage_const_1 ]+blocks[_sage_const_2 ]*x))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_27 , latex(blocks[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_28 , latex(blocks[_sage_const_4 ]*x-blocks[_sage_const_5 ]))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_29 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_30 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_31 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_32 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_33 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_126 )
_st_.current_tex_line = _sage_const_129 
_st_.blockbegin()
try:
 problemNumber = _sage_const_10 
 load("../Code/linear/solveRationalLinear.sage")
except:
 _st_.goboom(_sage_const_132 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_34 , latex(displayStem))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_35 , latex(coefficients[_sage_const_0 ] * x + numerators[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_36 , latex(denominators[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_37 , latex(coefficients[_sage_const_1 ] * x + numerators[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_38 , latex(denominators[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_39 , latex(coefficients[_sage_const_2 ] * x + numerators[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_40 , latex(denominators[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_41 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_42 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_43 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_44 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_45 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_148 )
_st_.endofdoc()

